version: '3'
services:
  proxy:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - jomon-server
      - jomon-client

  jomon-server:
    build:
      context: ./
      dockerfile: ./development/Dockerfile
      args:
        - GO_BUILD_TAGS=debug
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s
    command: fresh
    environment:
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: password
      MARIADB_HOSTNAME: db
      MARIADB_DATABASE: jomon
      GO_BUILD_TAGS: debug
    ports:
      - '1323:1323'
    volumes:
      - './:/src'
    depends_on:
      - db

  jomon-client:
    build: ./client
    volumes:
      - './client/app'
    tty: true
    entrypoint: npm run serve

  db:
    image: mariadb:10.3.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: jomon
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - '3306'
    ports:
      - '3306:3306'
