version: '3'
services:
  jomon-server:
    image: swaggermock/swagger-mock
    environment:
      SWAGGER_MOCK_SPECIFICATION_URL: "/docs/swagger.yaml"
    ports:
      - '1323:8080'
    volumes:
      - './docs:/docs'
