version: '3'
services:

  jomon-server:
    image: swaggermock/swagger-mock
    environment:
      SWAGGER_MOCK_SPECIFICATION_URL: "/docs/swagger.yaml"
    ports:
      - '1323:8080'
    volumes:
      - './docs:/docs'

  jomon-client:
    build: ./client
    ports:
      - '3000:8080'
    volumes:
      - './client/app'
    tty: true
    entrypoint: npm run serve