version: '2'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps: [build]
    cmds:
      - /app/Jomon
    sources:
      - '**/*.go'

  build:
    dir: /src
    cmds:
      - go build -tags debug -o /app/Jomon
