openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: '/api'
info:
  version: "1.0.0"
  title: Jomon API
  description: >-
    JomonのAPIです。
security:
  - application:
      - read
      - write
paths:
  '/applications':
    get:
      description: 申請書一覧を取得する。
      tags:
        - Applications
      parameters:
        - name: sort
          description: |
            並び順 (作成日時が新しい "created_at", 作成日時が古い "-created_at", タイトルの昇順 "title",
            タイトルの降順 "-title")
          required: false
          in: query
          schema:
            type: string
        - name: current_state
          description: 現在の申請書の状態（"applied","rejected","fix_required","permitted","paid")
          required: false
          in: query
          schema:
            type: string
        - name: applicant
          description: 誰が申請したか
          required: false
          in: query
          schema:
            type: string
        - name: type
          description: どのタイプか（"Club","Contest","Event","Public")
          in: query
          required: false
          schema:
            type: string
        - name: applied_since
          description: いつからの申請か
          required: false
          in: query
          schema:
            type: string
            format: date
        - name: applied_until
          description: いつまでの申請か
          required: false
          in: query
          schema:
            type: string
            format: date
      responses:
        "200":
          description: 取得できた。返す。該当するものがなくても空配列を返す。
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                      example: "冬コミの交通費です"
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: data_time
                    aplicant:
                      $ref: "#/components/schemas/User"
                    current_state:
                      type: string
                      example: "fix-requied"
                    ammount:
                      type: integer
                      example: 1200
        "400":
            description: リクエストがおかしい。
    post:
      description: 申請書を新規作成する。
      tags:
        - Applications
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PostApplication"
      responses:
        "201":
          description: 作成した。作成した先を返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: "申請書のレコードid"
                  application_id:
                    type: integer
                    example: "同一申請書ごとのid"
                  created_at:
                    type: string
                    format: "date-time"
                    example: "2019/07/28 22:00:00"
                  current_state:
                    type: string
                    example: "rejected"
                  application: 
                    $ref: "#/components/schemas/Application"

        "400":
          description: リクエストに形式上または内容の不備がある。例えばtitleが空欄である、amountが負である,指定されたpaid_by_idに該当するClientが存在しないなど。内容に不備がある場合には、不備があるkeyを配列にして返す。
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "ammout"
  "/applications/{applicationId}":
    get:
      description: 指定した申請書の詳細を取得する。
      tags:
        - Applications
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: あったら返す。
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: "申請書のレコードid"
                  application_id:
                    type: integer
                    example: "同一申請書ごとのid"
                  created_at:
                    type: string
                    format: "date-time"
                    example: "2019/07/28 22:00:00"
                  current_state:
                    type: string
                    example: "rejected"
                  application: 
                    $ref: "#/components/schemas/Application"
                  comments_logs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Comment"
                  state_logs:
                    type: array
                    items:
                      $ref: "#/components/schemas/State"
                  application_logs:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          $ref: "#/components/schemas/Application"
                        updated_at:
                          type: string
                          format: date-time
        "400":
          description: リクエストがおかしい。
        "404":
          description: 指定されたApplicationIdはない。
    patch:
      description: 指定したApplicationを修正する。(新しいレコードを作る）。修正できるのは申請書の作成者かadminで、かつstateが"applied"(申請済み)もしくは"fix_required"(要修正))のとき。
      tags:
        - Applications
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PostApplication"
      responses:
        "200":
          description: 修正できた。返す。
          content:
            application/json:
             schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: "申請書のレコードid"
                  application_id:
                    type: integer
                    example: "同一申請書ごとのid"
                  created_at:
                    type: string
                    format: "date-time"
                    example: "2019/07/28 22:00:00"
                  current_state:
                    type: string
                    example: "rejected"
                  application: 
                    $ref: "#/components/schemas/Application"
        "400":
          description: リクエストに形式上または内容の不備がある。例えばtitleが空欄である、amountが負である,指定されたpaid_by_idに該当するClientが存在しないなど。内容に不備がある場合には、不備があるkeyを配列にして返す。
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  example: "ammout"
        "403":
          description: 編集権限がない人による操作または編集できないstate
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_user_permitted:
                    type: boolean
                    example: fales
                  current_state:
                    type: string
                    example: "rejected"
        "404":
          description: 指定された申請書はない。
  "/applications/{applicationId}/comment":
    post:
      description: 指定した申請書にコメントを新規作成する。
      tags:
        - Comments
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  example: "ここを修正してください。"
      responses:
        "200":
          description: OK
          content:
            application/json:
             schema:
                    $ref: "#/components/schemas/Comment"
        "400":
          description: リクエストに形式上または内容の不備がある。例えばコメント欄が空欄。
        "404":
          description: 指定された申請書はない。
  "/applications/{applicationId}/states":
    put:
      description: 指定した申請書のstateを変更のみ（新規はpost /applications で)する。reasonについてはstateを「appliedからfix_required」「appliedからrejected」「permittedからapplied」にするとき必須。stateの行き来の定義は作成者は「fix_requiredからapplied（このときapplication更新も行なっているはず）」をでき、adminは「appliedからrejected」「appliedからrequired」「fix_requiredからapplied」「appliedからpermitted」「permittedからapplied」「permittedからpaid」の操作のみ可。
      tags:
        - States
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to_state:
                  type: string
                  example: "permitted"
                reason:
                  type: string
                  example: "良いですね。"
      responses:
        "200":
          description: OK
          content:
            application/json:
             schema:
              type: object
              properties:
                user:
                  $ref: "#/components/schemas/User"
                updated_at:
                  type: string
                  format: date-time
                current_state:
                  type: string
                  example: "permitted"
                past_state:
                  type: string
                  example: "rejected"
        "400":
          description: リクエストに形式上または内容の不備がある。または行き来できないstate。
        "403":
          description: 編集権限がない人による操作。
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_user_permitted:
                    type: boolean
                    example: fales
                  current_state:
                    type: string
                    example: "rejected"
                  to_state:
                    type: string
                    example: "paid"
        "404":
          description: 指定された申請書はない。
  "/users":
    get:
      description: ユーザの一覧を返す
      tags:
        - Users
      responses:
        "200":
          description: 取得に成功した。返す
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      $ref: "#/components/schemas/User"
                    admin:
                      type: boolean
  "/users/me":
    get:
      tags:
        - Users
      description: 自分のユーザー情報を取得します
      responses:
        '200':
          description: 正常に取得できました。
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  "/users/admin":
    get:
      description: adminユーザの一覧を返す。
      tags:
        - Users
      responses:
        "200":
          description: 取得に成功した。返す
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    user:
                      $ref: "#/components/schemas/User"
                    admin:
                      type: boolean
    put:
      description: adminユーザーを変更する。
      tags:
        - Users
      requestBody:
        required: true
        content:
            application/json:
              schema:
                  type: object
                  properties:
                    trap_id:
                      type: string
                      example: "nagatech"
                    to_admin:
                      type: boolean
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    user:
                      $ref: "#/components/schemas/User"
                    current_admin:
                      type: boolean

        "400":
          description: リクエストに形式上または内容の不備がある。例えばadminの状態が変更前と同じだった時。
        "403":
          description: admin以外の人
        "404":
          description: adminを変更しようとした対象者は存在しない

components:
  schemas: 
    Application:
      type: object
      properties:
        type:
          type: string
          example: "Public"
        title:
          type: string
          example: "夏コミの交通費をお願いします。"
        remarks:
          type: string
          example: "〇〇駅から〇〇駅への移動"
        ammount:
          type: integer   
          example: 1200
        paid_to_id:
          type: array
          items: 
            type: string
            example: "nagatech"
        image_name:
          type: array
          items: 
            type: string
            example: "画像の保管場所を表す何か"
    PostApplication:
      type: object
      properties:
        adress:
            type: object
            properties:
              type:
                type: string
                example: "Public"
              title:
                type: string
                example: "夏コミの交通費をお願いします。"
              remarks:
                type: string
                example: "〇〇駅から〇〇駅への移動"
              ammount:
                type: integer   
                example: 1200
              paid_to_id:
                type: array
                items: 
                  type: string
                  example: "nagatech"
        image_name:
          type: array
          items: 
            type: string
            format: binary
    User:
      type: object
      properties:
        trap_id:
          type: string
          example: "nagatech"
        display_name:
          type: string
          example: "ながてち"
        icon_filed:
          type: string
          example: "e0628393-8045-4c6c-b23c-6f5e6a2c252b"
    Comment:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
        comment:
          type: string
          example: "コメント内容"
        created_at:
          type: string
          format: "date-time"
          example: "2019/07/28 22:00:00"
    State:
      type: object
      properties:
        user:
          $ref: "#/components/schemas/User"
        to_state:
          description: 申請済み(applied) ,却下(rejected),要修正(fix_required),許可済み(permitted),返金済み(paid)
          type: string
          example: "rejected"
        reason:
          type: string
          default: null
          example: "これは雑すぎますね。"
        created_at:
          type: string
          format: "date-time"
          example: "2019/07/28 22:00:00"
  securitySchemes:
    application:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources
            
